# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c506a2744814a8fc34ff97316ba1886868e595d0ca57b0c2ad86f9e7289102a92f4a7295ac2af8759f5d97655192305811e0ce704bda999e05a6b66bc8385bf

test:
  secret_key_base: 6fce910064772d149d0aa3212e54bbb3e3ccd182d2a67c24fb1cd99864e9b042a179b5b063971c5c8b2561cefa57aa6c62c62d6dc7bf2cd97aabdebfb6b895df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
